import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/layout/navbar'
import Footer from '@/components/layout/footer'
import { Suspense } from 'react'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'text-slate-800')}>
        <Navbar />
        <Suspense>
          <main className='bg-stone-100 min-h-dvh'>
            {children}
          </main>
        </Suspense>
        <Footer />
      </body>
    </html>
  )
}
